DROP DATABASE IF EXISTS ua_quiz;
DROP ROLE IF EXISTS quiz_role;
DROP USER IF EXISTS quiz;

CREATE USER quiz WITH PASSWORD 'quiz' CREATEDB;
CREATE ROLE quiz_role WITH SUPERUSER USER quiz;

CREATE DATABASE ua_quiz
WITH OWNER = quiz
ENCODING = 'UTF8';